### ISSUE TITLE
Question about ValueNoise.png

### ISSUE THREAD

**Issue by griderd** [Flafla2/Raymarch-Clouds#2]
I am curious as to how the value noise file was generated, and why it is 256x256. I am not an expert in shader languages or raymarching, so I'm having a hard time reverse-engineering noise system or how it works.

Any help would be appreciated. I would like to generate different patterns for different kinds of cloud coverage.

**Comment by Flafla2** [comment]
That's simply random values from 0-255 in R, G, and B channels.  IIRC I just went into GIMP and used a command under the Filters -> Noise menu to generate it.

The basic Idea is sample the value noise at different frequencies with amplitude decreasing as frequency increases.  If you add them all together, you get something that looks like a terrain / clouds etc (low freq, high amplitude = large sweeping features; high freq low amplitude = small perturbations).

Check out the end of my [article on perlin noise](http://flafla2.github.io/2014/08/09/perlinnoise.html) for more info ("Working with Octaves").  Perlin Noise is different than value noise (higher quality but more math intensive).  Since raymarching needs to sample the noise a ton of times (number of pixels times number of ray march steps) I opted to go with texture lookups (into the value noise table) instead of math.
